spring.application.name=thymeleaf_test

# Variables cargadas desde .env por la clase EnvConfig
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/${DB_TYPE}


#conf old
# Conexion a Base de Datos H2 persistente en archivo
#spring.datasource.url=jdbc:h2:file:./data/librotech_db
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

# Configuracion Hibernate / JPA
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
# ===== HIBERNATE: Delegamos el esquema a Flyway =====
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=true
#spring.jpa.defer-datasource-initialization=true

# Consola H2 para visualizacion
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# ===== FLYWAY =====
#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration
#spring.flyway.baseline-on-migrate=false

